# Generated by Django 5.0 on 2024-01-08 15:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invoices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField()),
                ('CustomerName', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='InvoicesDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('quantity', models.PositiveIntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('invoices', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Invoices.invoices')),
            ],
        ),
    ]
