# Generated by Django 5.0.1 on 2024-01-08 17:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Invoices', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicesdetails',
            name='invoices',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Invoices.invoices'),
        ),
    ]
